# Generated by Django 5.1.3 on 2024-12-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstall', '0003_attendancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
