# Generated by Django 5.1.3 on 2024-12-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstall', '0004_employee_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='per_day_wage',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='per_hour_wage',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
