# Generated by Django 5.1.3 on 2024-12-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstall', '0005_employee_per_day_wage_employee_per_hour_wage'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='per_min_wage',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
