# Generated by Django 5.1.3 on 2025-01-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstall', '0006_employee_per_min_wage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='per_day_wage',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='per_hour_wage',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='per_min_wage',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
        migrations.AddField(
            model_name='employee',
            name='days_to_deduct',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='early_logouts_late_logins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(default='unknown', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
