# Generated by Django 5.1.3 on 2025-01-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstall', '0007_remove_employee_per_day_wage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
