# Generated by Django 5.1.3 on 2025-01-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstall', '0008_alter_employee_email_alter_employee_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(default='unknown', max_length=50, unique=True),
        ),
    ]
